### ISSUE TITLE
Analyze bit-for-bit failure for test_datm_lnd

### ISSUE THREAD

**Issue by danrosen25** [esmf-org/noahmp#11]
Review failure for https://github.com/esmf-org/noahmp/actions with push
https://github.com/esmf-org/noahmp/commit/246570ca4cda03278fd785f5f4173a92156e3944

**Comment by danrosen25** [comment]
Add runtime checking to build for NoahMP including initialization checks and floating point exceptions. Use ESMF build with BOPT=g. Look through the ESMF compiler options for BOPT=g.
```
ESMF_F90OPTFLAG_G       += -Wall -Wextra -Wconversion -Wno-unused -Wno-unused-dummy-argument -fbacktrace -fimplicit-none -fcheck=all,no-pointer
ESMF_CXXOPTFLAG_G       += -Wall -Wextra -Wno-unused $(ESMF_LINKOPTFLAG_G)
```

**Comment by uturuncoglu** [comment]
The build flags are tested but not helped. In addition to that I performed following tests,

- I could able to build UFS Weather Model under docker container with couple of minor fixes. This uses regular UFS and includes CDEPS+CMEPS+UFS Driver+NOAHMP. Then, I used the executable to run datm+land configuration. In this case, I used esmf-8.4.0b15 (non-optimized - g) and I have no reproducibility issue.

- I tried it again with the optimized version of ESMF (esmf-8.4.0b15 - O) and that is also fine under UFS.

- Then, I tried to have the same configuration with ESMX to see if there is an issue in manual component builds. In this case, i used components build from UFS. So, I did not build them manually. Then, I check the reproducibility and the results are not reproducing. This is interesting since when ESMX and connectors are introduced (the reproduced runs was using CMEPS and UFS driver), the answer starting to change. 

So, at this point I think the issue is not related with the build of individual components but maybe related with the used interpolation type in connector case or in ESMX build. Here is my run sequence,

runSeq::
@3600
  LND -> ATM :remapMethod=bilinear:unmappedaction=ignore:zeroregion=select
  ATM -> LND :remapMethod=bilinear:unmappedaction=ignore:zeroregion=select
  ATM
  LND
@
::

The CMEPS runs is using mapnstod_consf for data configuration and here is the call for it in CMEPS side

       call ESMF_FieldRegridStore(fldsrc, flddst, routehandle=routehandles(mapconsf), &
            srcMaskValues=(/srcMaskValue/), &
            dstMaskValues=(/dstMaskValue/), &
            regridmethod=ESMF_REGRIDMETHOD_CONSERVE, &
            normType=ESMF_NORMTYPE_FRACAREA, &
            srcTermProcessing=srcTermProcessing_Value, &
            ignoreDegenerate=.true., &
            dstStatusField=dststatusfield, &
            unmappedaction=ESMF_UNMAPPEDACTION_IGNORE, &
            rc=rc)

       call ESMF_FieldRegridStore(fldsrc, flddst, routehandle=routehandles(mapnstod), &
            srcMaskValues=(/srcMaskValue/), &
            dstMaskValues=(/dstMaskValue/), &
            regridmethod=ESMF_REGRIDMETHOD_NEAREST_STOD, &
            srcTermProcessing=srcTermProcessing_Value, &
            ignoreDegenerate=.true., &
            dstStatusField=dststatusfield, &
            unmappedaction=ESMF_UNMAPPEDACTION_IGNORE, &
            rc=rc)

So, I could also try to use conservative interpolation with the connector configuration (ESMX) and see what happens but do we expect answer change with bilinear. Other possible test could be changing interpolation type under CMEPS to bilinear and run it to see if it changes the answer or not like ESMX. If it has issue with reproducibility, then we could blame the interpolation type (bilinear in here) for answer change and we could look at it more closely. Still investigating the issue.

**Comment by uturuncoglu** [comment]
This is solved by updating the run sequence as following,

```
runSeq::
@3600
  LND -> ATM :remapMethod=bilinear:unmappedaction=ignore:zeroregion=select:srcTermProcessing=0:termOrder:srcseq
  ATM -> LND :remapMethod=bilinear:unmappedaction=ignore:zeroregion=select:srcTermProcessing=0:termOrder:srcseq
  ATM
  LND
@
```
